spring:
  datasource:
    type: org.springframework.jdbc.datasource.DriverManagerDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.143.231.137:3306/agileboot?characterEncoding=utf-8&useSSL=false
    username: root
    password: Aa20341103

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging.level.com.example: debug