spring:
  datasource:
    type: org.springframework.jdbc.datasource.DriverManagerDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/agileboot?characterEncoding=utf-8&useSSL=false
    username: root
    password: Aa20341103